const {test}=require('node:test'),assert=require('node:assert/strict');
const Y=require('../static/youtube-core.js'),C=require('../static/core.js');
const ID='M7lc1UVf-VE'; // Official YouTube developer documentation demo ID; captions below are synthetic.
const RAW="00:12.200 --> 00:16.700\nI was thinking of taking a break.\n\n00:17.100 --> 00:21.000\nThen I came up with a different plan.";
const make=()=>Y.card({id:ID,title:'Fixture'},Y.cues(RAW)[0],{expression:'thinking of',meaning_ko:'~할까 생각하다'});
test('YouTube links normalize common formats and reject foreign or executable URLs',()=>{for(const url of ['https://youtu.be/'+ID+'?t=1m2s','https://www.youtube.com/watch?v='+ID+'&t=62','https://www.youtube.com/shorts/'+ID+'?start=62'])assert.deepEqual(Y.video(url),{id:ID,start:62,url:Y.watch(ID,62)});for(const url of ['javascript:alert(1)','https://youtube.com.evil.example/watch?v='+ID,'https://youtube.com@evil.example/watch?v='+ID,'https://youtube.com/playlist?list=foo','https://youtube.com/watch?v=no'])assert.throws(()=>Y.video(url));});
test('caption times preserve fractions and reject invalid ranges',()=>{assert.equal(Y.time('01:02:03,125'),3723.125);assert.equal(Y.time('1:67'),null);assert.equal(Y.time('-2'),null);assert.equal(Y.time(Y.captionStamp(.125)),.125);assert.equal(Y.time(Y.captionStamp(86400)),86400);assert.throws(()=>Y.cues('0:15 --> 0:12\nText'));});
test('SRT, VTT and copied YouTube captions preserve grounded source lines',()=>{const srt=Y.cues('1\n00:00:01,250 --> 00:00:03,750\nI was thinking of going.\n\n2\n00:00:04,000 --> 00:00:06,000\nLet us make sure.');assert.equal(srt[0].start,1.25);assert.equal(srt[0].end,3.75);assert.equal(srt.length,2);const vtt=Y.cues('WEBVTT\n\n00:01.200 --> 00:03.500 align:start\n<b>Take care of</b> it.');assert.equal(vtt[0].text,'Take care of it.');const copy=Y.cues('0:12\nI was thinking of going.\n0:17\nI came up with a plan.');assert.equal(copy[0].end,17);assert.equal(copy[1].estimated,true);});
test('untimed text never gets fabricated source timestamps',()=>{const xs=Y.cues('I was thinking of leaving.\nBut I changed my mind.');assert.equal(xs[0].start,null);assert.equal(xs[0].end,null);const c=Y.card({id:ID},xs[0],{expression:'thinking of',meaning_ko:'생각하다'});assert.equal(c.media.start,null);assert.equal(c.media.end,null);assert.ok(!Y.embed(ID,null,null).includes('start='));});
test('rule candidates are actual source substrings and cannot invent expression matches',()=>{const xs=Y.cues(RAW);const found=Y.suggest(xs);assert.equal(found.length,2);for(const p of found)assert.ok(xs.find(c=>c.id===p.cue_id).text.includes(p.expression));assert.deepEqual(Y.suggest(Y.cues('0:00\nPurple flowers.')),[]);});
test('custom YouTube cards reject unsafe links and fabricated quotes',()=>{const c=make();assert.ok(Y.validCard(c));for(const edit of [x=>x.source_url='javascript:alert(1)',x=>x.media.video_id='invalid',x=>x.expression='not in the original',x=>x.media.end=x.media.start-1,x=>x.id='g01_01']){const bad=structuredClone(c);edit(bad);assert.equal(Y.validCard(bad),false);}});
test('YouTube cards and their review history survive a fresh backup import',()=>{const c=make(),s=C.initialState();s.customCards=[c];s.cards[c.id]={due:123};s.lastExerciseId='single_'+c.id;s.lastLessonId='youtube';const restored=C.migrateState(JSON.parse(JSON.stringify(s)),new Map());assert.equal(restored.customCards[0].id,c.id);assert.equal(restored.cards[c.id].due,123);const bad=structuredClone(s);bad.customCards[0].source_url='https://evil.example/';assert.throws(()=>C.migrateState(bad,new Map()));});
test('ChatGPT expression import verifies video and exact source, ignores model timestamps',()=>{const xs=Y.cues(RAW),reply={video_id:ID,items:[{cue_id:xs[0].id,source_text:xs[0].text,expression:'thinking of',meaning_ko:'생각하다',start:800,end:820,new_task_ko:'휴가 계획을 말하세요.',new_sample_en:'I was thinking of taking a week off.'}]};const got=Y.importItems(JSON.stringify(reply),{id:ID},xs);assert.equal(got[0].card.media.start,xs[0].start);assert.ok(got[0].task);reply.items[0].source_text='Invented quote.';assert.throws(()=>Y.importItems(JSON.stringify(reply),{id:ID},xs));});

test('adjacent subtitle fragments form one grounded phrase with the actual time span',()=>{const raw=Y.cues('00:00:10.100 --> 00:00:12.000\nI was thinking\n\n00:00:12.000 --> 00:00:14.300\nof taking a break.\n\n00:00:20.000 --> 00:00:22.000\nA different scene.');const merged=Y.studyCues(raw);assert.equal(raw.length,3);assert.equal(merged.length,2);assert.equal(merged[0].text,'I was thinking of taking a break.');assert.equal(merged[0].start,10.1);assert.equal(merged[0].end,14.3);assert.equal(Y.suggest(merged)[0].expression,'I was thinking of');assert.equal(Y.studyCues(Y.cues('Untimed phrase.\nAnother untimed phrase.')).length,2);});
test('a caption piece cut mid-sentence is joined with the words that finish it',()=>{
 const raw='7:20\nSo I want to ask you a question.\n7:33\nBut if you don\'t know why you do what you do, and people respond to why you do what you do, then how will you ever get people to vote for you, or buy something from you, or, more importantly, be loyal\n7:46\nand want to be a part of what it is that you do.\n7:50\nAgain, the goal is not just to sell.';
 const out=Y.studyCues(Y.cues(raw));
 assert.equal(out.length,3);assert.match(out[1].text,/be loyal and want to be a part of what it is that you do\.$/);assert.equal(out[1].chunk_kind,'sentence');
 assert.equal(out[1].start,453);assert.equal(out[1].end,470);
});
test('joining stops at 90 words and never runs over a long pause or unpunctuated captions',()=>{
 const long=Array.from({length:7},(_,i)=>Y.captionStamp(i*4)+'\n'+'we kept talking about the plan for the week and '.repeat(2).trim()).join('\n')+'\n0:28\nthen we stopped.';
 assert.ok(Y.studyCues(Y.cues(long)).every(c=>c.text.split(/\s+/).length<=90));
 const gap=Y.studyCues(Y.cues('0:00 --> 0:04\nI went to the market\n0:30 --> 0:34\nand bought some bread.'));assert.equal(gap.length,2);
 const flat=Array.from({length:12},(_,i)=>Y.captionStamp(i*3)+'\nso we went to the store and then we talked about it for a while').join('\n');
 assert.ok(Y.studyCues(Y.cues(flat)).every(c=>c.text.split(/\s+/).length<=60));
});
