const {test}=require('node:test'),assert=require('node:assert/strict');
const A=require('../static/auto-lessons'),Y=require('../static/youtube-core'),C=require('../static/core');
const ID='M7lc1UVf-VE',parse=s=>Y.studyCues(Y.cues(s));
const sentence="Has that been such a surprise to see how like massive it's gotten just right when your album comes out.";
const screenshot="It's like no. "+sentence+" It's crazy. I was just saying even";
test('all caption sentences stay whole, including short replies and unpunctuated tails',()=>{const cues=parse('0:02\n'+screenshot),r=A.builtin({id:ID},cues);assert.deepEqual(r.items.map(x=>x.expression),["It's like no.",sentence,"It's crazy.",'I was just saying even']);const item=Y.importItems(JSON.stringify(r),{id:ID},cues)[1];assert.equal(item.card.expression,sentence);assert.equal(item.sample,sentence);assert.equal(item.card.media.start,2);});
test('unknown phrases still produce sentence practice without invented translations',()=>{for(const sentence of ['The cat comes out of the box.','A crystal prism refracts light.']){const r=A.builtin({id:ID},parse(sentence));assert.equal(r.items.length,1);assert.equal(r.items[0].expression,sentence);assert.equal(r.items[0].meaning_ko,'문장 통째로 듣고 다시 말하기');}assert.ok(!A.builtin({id:ID},parse('The cat comes out of the box.')).items[0].note_ko.includes('출시'));});
test('whole video returns all 623 sentences without the old batch and JSON limits',()=>{const cues=parse(Array.from({length:623},(_,i)=>Y.captionStamp(i*5)+'\nI would like to tell you about project number '+i+'.').join('\n'));const r=A.builtin({id:ID},cues);assert.equal(r.items.length,623);assert.equal(r.items.at(-1).expression,cues.at(-1).text);for(const x of r.items)assert.equal(x.expression,cues.find(c=>c.id===x.cue_id).text);});
test('repeated utterances keep their separate source positions and non-speech labels are excluded',()=>{const cues=parse('0:00\nYes. Yes.\n0:05\nYes.\n0:10\n[Music]\n0:15\nI was just saying even');const r=A.builtin({id:ID},cues);assert.deepEqual(r.items.map(i=>i.expression),['Yes.','Yes.','Yes.','I was just saying even']);assert.deepEqual(r.items.map(i=>i.cue_id),['cue_0','cue_1','cue_2','cue_4']);assert.equal(Y.importItems(JSON.stringify(r),{id:ID},cues).length,4);});
test('source recall prompt and complete sentence survive backup restore',()=>{const cues=parse('0:02\n'+sentence),item=Y.importItems(JSON.stringify(A.builtin({id:ID},cues)),{id:ID},cues)[0],c=item.card;Object.assign(c,{practice_task_ko:item.task,practice_sample_en:item.sample,practice_origin:'자막 원문 · 문장 회상',chunk_kind:'sentence',meaning_source:'none'});const s=C.initialState();s.customCards=[c];const restored=C.migrateState(JSON.parse(JSON.stringify(s)),new Map());assert.equal(C.cardExercise(restored.customCards[0]).sample_en,sentence);delete c.practice_task_ko;assert.equal(Y.validCard(c),false);});
test('untimed sentences preserve missing positions',()=>{const cues=parse('I was thinking of taking a break.'),c=Y.importItems(JSON.stringify(A.builtin({id:ID},cues)),{id:ID},cues)[0].card;assert.equal(c.media.start,null);assert.equal(c.media.end,null);assert.ok(Y.validCard(c));});
test('sentence splitter preserves abbreviations and decimal values',()=>{assert.deepEqual(Y.sentenceParts('Dr. Smith paid $3.50 for it. I really enjoyed our visit.'),['Dr. Smith paid $3.50 for it.','I really enjoyed our visit.']);assert.deepEqual(Y.sentenceParts('What did you think? I thought it was great!'),['What did you think?','I thought it was great!']);});
test('multiple sentences share their actual subtitle interval, not guessed word times',()=>{const xs=parse('00:02.125 --> 00:14.250\nI really enjoyed our trip to the coast. We should go back there next summer.');assert.equal(xs.length,2);for(const c of xs){assert.equal(c.start,2.125);assert.equal(c.end,14.25);assert.equal(c.estimated,true);}});
test('long unpunctuated captions produce bounded long speech chunks without added words',()=>{const raw=Array.from({length:120},(_,i)=>'word'+i).join(' '),xs=parse('0:00\n'+raw);assert.ok(xs.length>=3);assert.equal(xs.map(c=>c.text).join(' '),raw);for(const c of xs){assert.ok(c.text.split(' ').length>=5);assert.ok(c.text.split(' ').length<=60);assert.equal(c.chunk_kind,'speech');assert.equal(c.start,0);}});
test('sixty-card session survives reload with unique queue and saved position',()=>{const cues=parse(Array.from({length:60},(_,i)=>'I would like to talk about topic '+i+'.').join('\n')),items=Y.importItems(JSON.stringify(A.builtin({id:ID},cues,60)),{id:ID},cues);const s=C.initialState();s.customCards=items.map(i=>i.card);s.session={ids:s.customCards.map(c=>c.id),index:27,completed:[],skipped:[],at:0};const restored=C.migrateState(JSON.parse(JSON.stringify(s)),new Map());assert.equal(restored.session.ids.length,60);assert.equal(restored.session.index,27);s.session.ids.push(s.session.ids[0]);assert.throws(()=>C.migrateState(s,new Map()));});

test('a full 623-card speaking queue and translations survive backup round-trip',()=>{const cues=parse(Array.from({length:623},(_,i)=>'I would like to talk about topic '+i+'.').join('\n')),r=A.builtin({id:ID},cues),s=C.initialState();s.customCards=r.items.map((item,i)=>Y.card({id:ID},cues[i],item));for(const c of s.customCards)s.translations[c.id]={source_en:c.expression,korean_text:'이 주제에 대해 이야기하고 싶어요.',engine:'browser'};s.session={ids:s.customCards.map(c=>c.id),index:612,completed:[],skipped:[],at:0};const restored=C.migrateState(JSON.parse(JSON.stringify(s)),new Map());assert.equal(restored.customCards.length,623);assert.equal(restored.session.index,612);assert.equal(Object.keys(restored.translations).length,623);});
